### ISSUE TITLE
Refactor repository

### ISSUE THREAD

**Issue by BarinderBanwait** [JosuaKugler/sato-tate-distributions#1]
Hi @JosuaKugler ,

This is looking awesome! 👍🏾 

I do however have a few suggestions which will make it easier for me to review the code and hopefully more readable for others who'd be interested in your work.

1. Move all the source code into `.py` files, perhaps in a directory called `sage_src` or something.

This enables GitHub features like raising issues on specific lines of code, and allows for easier code reviewing. But perhaps more importantly, it allows people to clone this repo and run the code themselves in the sage terminal without having to use the notebook interface (i.e. it becomes more platform independent.)

2. In the current `.ipynb` files, after having removed the source code to other files, what you need from the source can be imported like any other python library, so these notebook files become the report of your findings; graphs, and discussion on conjectures in markdown cells. 

So e.g. in `vertical_st.ipynb`, you're using `plot_theta` and `plot_theta_interval` as the top-level functions quite a lot. Maybe all of that code could go into `sage_src/plot_utils.py`, and then at the top of `vertical_st.ipynb`, you'd do `from sage_src.plot_utils import plot_theta, plot_theta_interval`. Similarly for the other `.ipynb` files. At the moment the `ipynb` files have lots of code which perhaps detract from the mathematical essence of what you're trying to show about the convergence rate.

**Comment by JosuaKugler** [comment]
Hi @BarinderBanwait,
Thanks a lot! The notebooks are looking way cleaner now. I decided to make a separate source file for the vertical and the horizontal case as the definitions of Delta and theta are different  in those two cases.

**Comment by BarinderBanwait** [comment]
Thanks @JosuaKugler , looks much clearer now!
