### ISSUE TITLE
Why `my_prime_range`

### ISSUE THREAD

**Issue by BarinderBanwait** [JosuaKugler/sato-tate-distributions#3]
https://github.com/JosuaKugler/sato-tate-distributions/blob/2ea63d819e3198f6c3a48ddaf5dc206593a73f4a/sage_src/vertical_st.py#L25

Why can't you just use `prime_range`? Is this faster or something?

**Comment by JosuaKugler** [comment]
Somehow when importing sage files certain functions didn't work anymore, so I had to explicitly import them or write them by myself. Therefore it really took hours to port the code from notebooks to external files. However, I can try to find out the implicit import statement for normal prime_range and try to use that, maybe it'll work.

**Comment by JosuaKugler** [comment]
ok actually that was super easy, with `import_statements` I could find out where sage imported `prime_range` from so that I could include it in my files and don't need `my_prime_range` anymore

**Comment by BarinderBanwait** [comment]
oh right, sorry it took so long to find the correct imports. I do this by opening the sage terminal, and whatever I want to import into the python module (e.g. `prime_range` or `QQ`), just type that in sage, and then followed by `?`:


```
sage: prime_range?
```

You'll then see the `File:` where that function is imported from:

```
File:           ~/SageMath/local/lib/python3.9/site-packages/sage/rings/fast_arith.pyx
```
