### ISSUE TITLE
Give overview of functions in this file at top as a comment

### ISSUE THREAD

**Issue by BarinderBanwait** [JosuaKugler/sato-tate-distributions#4]
https://github.com/JosuaKugler/sato-tate-distributions/blob/2ea63d819e3198f6c3a48ddaf5dc206593a73f4a/sage_src/vertical_st.py#L1

There should be a high-level description of what the code in this file does. It seems mostly about plotting, computing L1 and L2 norms, and fast a_p computations.

Also, maybe give docstrings for some of the critical functions here, like `Delta`?

**Comment by JosuaKugler** [comment]
I added docstrings for all functions, gave a brief description what happens in vertical_st and horizontal_st and added a summary of all functions in the files

**Comment by BarinderBanwait** [comment]
Thanks -- though ideally the multi-line docstrings at the top of each module should be in `"""triple double quotes"""`:

https://peps.python.org/pep-0257/

So e.g. the top of `horizontal_st.py` should be:

```
"""horizontal_st.py
fast computations of sorted, normalized aplist of an elliptic curve
compute 'difference' between distribution for finite C and the 'semicircle" where difference is measured by L2-norm
take log and deal with error interval
finally provide nice plotting interfaces for all this
"""
```

(Generally adhering to [PEP8](https://peps.python.org/pep-0008/) for python is good practice.)
