### ISSUE TITLE
Code duplication?

### ISSUE THREAD

**Issue by BarinderBanwait** [JosuaKugler/sato-tate-distributions#5]
https://github.com/JosuaKugler/sato-tate-distributions/blob/2ea63d819e3198f6c3a48ddaf5dc206593a73f4a/sage_src/horizontal_st.py#L20

This function was also in `vertical_st`? Any functions common to both should probably go into a `utils.py` file which both import from.

**Comment by JosuaKugler** [comment]
as I'm using the sage prime_range now, I think there is no code duplication anymore. Some of the functions are pretty similar, but none of them is exactly the same and I'm not sure how easy it would be to put parts of these functions in a separate file

**Comment by JosuaKugler** [comment]
ok so indeed there is duplication as Xab is used in the vertical and the horizontal case

**Comment by JosuaKugler** [comment]
unfortunately importing utils isn't as easy as i thought, so probably I'll just add Xab to both files again
